### ISSUE TITLE
部署时不停的循环

### ISSUE THREAD

**Issue by recing** [fscarmen2/X-for-Daki#2]

**Comment by fscarmen2** [comment]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/92626977/212903881-8df47fd6-a966-4039-bb30-43a490ed4180.png">

<img width="983" alt="image" src="https://user-images.githubusercontent.com/92626977/216507372-e2cbfc6a-5177-41ab-a104-1cc9c52c491a.png">


要填cf上的地址，具体操作看主页说明，不过即使这个报错，应该也能使用的，这个Daki不需要保活的。

**Comment by recing** [comment]
大佬您好！非常感谢及时赐教。按照您的要求改成CF上的地址，部署还是循环不止，部署完成不了，也不能使用。详见附件，谢谢！
[请教.docx](https://github.com/fscarmen2/X-for-Daki/files/10576736/default.docx)

**Comment by recing** [comment]
大佬您好！非常感谢及时赐教。按照您的要求改成CF上的地址，部署还是循环不止，部署完成不了，也不能使用。详见附件，谢谢！
[请教.docx](https://github.com/fscarmen2/X-for-Daki/files/10576909/default.docx)

**Comment by fscarmen2** [comment]
你那个地址是 cc 结尾的，应该是daki给的地址，不是cf上的吧。cf要确保3件事
1.把ssl 设置为灵活
2.做一条cname ，绑定daki的域名（不含端口）
3.做一条origin rule ，绑定daki的端口

举例，你在cf上自定义的域名是 daki.vps.tk
这时你在其他的vps上用 curl -m8 http://daki.vps.tk ， 这里应该会有hello world 出来的，没有就是没有设置好。

**Comment by recing** [comment]
大佬您好！非常感谢及时赐教。自以为按您的要求做了，还是一样的，循环不止，不能完成部署，也不能使用。详情见附件，多谢赐教。
[新建大佬.docx](https://github.com/fscarmen2/X-for-Daki/files/10593820/default.docx)

**Comment by fscarmen2** [comment]
你加我tg，@fscarmen2

**Comment by recing** [comment]
按照更新后的要求重做，就好了！谢谢大佬！！
